### ISSUE TITLE
[Typo] Menu is display "Tap" instead of "Tab"

### ISSUE THREAD

**Issue by tristancaron** [alexandermalcin/intellij-platform-browser-plugin#2]
When we do a right click on a tab or an overlay on the `+` icon, it says "Tap" instead of "Tab"

![image](https://github.com/alexandermalcin/intellij-platform-browser-plugin/assets/9624669/78b5be50-ca47-465e-8871-687181f7e4dd)
![Screenshot 2024-01-18 at 3 00 08 PM](https://github.com/alexandermalcin/intellij-platform-browser-plugin/assets/9624669/a02331db-bbce-4c96-93ed-38f1c8c9f86b)

**Comment by alexandermalcin** [comment]
Shame on me. Thanks man! It has been corrected and will hopefully be available very soon. Thanks for your input.
